config/routes.rb
CogsScreen::Application.routes.draw do
  get "floor_plan/show"

  if Rails.env.development?
    get "dev/sha"
  end

  root :to => "posts#all"

  get "posts" => "posts#all"
  get "posts/new"
  get "posts/destroy"
  get "posts/all"
  post "posts/add_user"
  delete "posts/del_user"
  resources :posts

  get "games/new"
  resources :games

  get "logout" => "sessions#destroy", :as => "logout"

  get "login" => "sessions#new", :as => "login"
  resources :sessions

  get "users/edit"
  get "signup" => "users#new", :as => "signup"
  resources :users

end

app/models/game.rb
class Game < ActiveRecord::Base
  attr_accessible :name, :url

  validates :name, :presence => true, :length => { :maximum => 40 }
  validates :url, :length => { :maximum => 200 }

  has_many :posts
  belongs_to :user

  def this
    self
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :users, :game, :params

  validates :game, :presence => true
  validates :params, :length => {:maximum => 80}

  has_and_belongs_to_many :users
  belongs_to :game
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :username, :comment, :ip, :table, :seat

  validates :ip, :presence => true
  if Rails.env != "development"
    validates :ip, :uniqueness => true
  end
  validates :username, :presence => true, :uniqueness => true, :length => { :maximum => 20 }
  validates :table, :presence => true
  validates :seat, :presence => true

  has_many :games
  has_and_belongs_to_many :posts

  def self.authenticate(username, ip)
    user = User.find_by_ip(ip)

    if user != nil and user.username == username
      user
    else
      nil
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/dev_controller.rb
class DevController < ApplicationController
  def sha
    wd = File.absolute_path( Dir.getwd() )
    Dir.chdir(File.dirname(__FILE__))
    result = `git log --name-status HEAD^..HEAD`
    Dir.chdir(wd)
    render :text => result.gsub("\n", '<br>').html_safe
  end
end

app/controllers/floor_plan_controller.rb
class FloorPlanController < ApplicationController
  def show
    @tables = TABLES
    @longest_name = 0
    User.all.each do |user|
      if user.username.length > @longest_name
        @longest_name = user.username.length
      end
    end
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def new
    @game = Game.new
  end

  def create
    if session[:user_id]
      if Game.find_by_name(params[:game][:name]) != nil
        flash.now[:notice] = "Game already exists!"
        render action: "new"
      else
        @game = Game.new(params[:game])

        if @game.url? and !@game.url.start_with?("http")
          @game.url = "http://" + @game.url
        end

        if @game.save
          redirect_to posts_new_url :notice => "Created " + @game.name
        else
          render action: "new"
        end
      end
    else
      flash.now[:notice] = "Must be registered!"
      render action: "new"
    end
  end

  def all
    @games = Game.all.sort { |a,b| a.name <=> b.name }
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def all
    @posts = Post.all.sort {|x,y| x.game.name <=> y.game.name}
  end

  def new
    @post = Post.new
  end

  def create
    user = User.find(session[:user_id])
    game = Game.find(params[:post][:game])
    @post = Post.where(:game_id => game.id, :params => params[:post][:params]).first

    if @post.nil?
      @post = Post.new(:game => game, :params => params[:post][:params])
    else
      if @post.users.include? user
        redirect_to new_post_path, :notice => "You have already requested that game!"
        return
      end
    end

    @post.users << user
    if @post.save
      redirect_to root_url, :notice => "Successfully created post!"
    else
      redirect_to new_post_path, :notice => "Post not created!"
    end
  end

  def destroy
    respond_to do |format|
      if Post.destroy(params[:id])
        format.html { redirect_to root_url }
        format.js { render :nothing => true }
      else
        format.html { flash[:notice] = "Something went wrong!" }
        format.js
      end
    end
  end

  def add_user
    @post = Post.find(params[:post_id])
    user = User.find(session[:user_id])
    respond_to do |format|
      if !@post.users.include? user
        @post.users << user
        format.html { redirect_to root_url }
        format.js { render :nothing => true }
      else
        format.html { flash[:notice] = "You have already requested this game!" }
        format.js
      end
    end
  end

  def del_user
    respond_to do |format|
      if Post.find(params[:id]).users.delete(User.find(session[:user_id]))
        format.html { redirect_to root_url }
        format.js { render :nothing => true }
      else
        format.html { flash[:notice] = "Something went wrong!" }
        format.js
      end
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.authenticate(params[:username], request.remote_ip)
    if user
      session[:user_id] = user.id
      redirect_to root_url, :notice => "Hello again, " + params[:username] + "!"
    elsif User.find_by_username(params[:username]).nil?
      flash.now[:notice] = "No user exists with that username. Please sign up."
      render "new"
    else
      flash.now[:notice] = "Invalid username for this IP address!"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :get_tables

  def get_tables
    @tables = []
    @seats = []
    TABLES.each do |table|
      @tables << table["name"]

      extras = 0
      if END_TABLES[table["name"]].include? "L"
        extras += 1
      end
      if END_TABLES[table["name"]].include? "R"
        extras += 1
      end

      table["rows"].each do |row|
        for j in 1..table["tables"]
          for i in 1..table["seats_per_table"] + extras
            seat_name = row + ((j-1)*table["seats_per_table"] + (i-1)).to_s
            if !@seats.include? seat_name
              @seats << seat_name
            end
          end
        end
      end
    end
  end

  def new
    @user = User.new
    @user.ip = request.remote_ip
  end

  def create
    params[:user][:ip] = request.remote_ip
    @user = User.new(params[:user])

    if User.exists?(:ip => @user.ip)
      flash.now[:notice] = "You have already registered from this ip address"
      render "new"
    elsif !SEATS[params[:user][:table]].include?(params[:user][:seat])
      flash.now[:notice] = "Seat is not on selected table"
      render "edit"
    elsif !User.where(:table => params[:user][:table], :seat => params[:user][:seat]).empty?
      flash.now[:notice] = "Someone else is sat there!"
      render "edit"
    elsif @user.save
      session[:user_id] = @user.id
      redirect_to root_url, :notice => "Welcome, " + @user.username + "!"
    else
      render "new"
    end
  end

  def edit
    @user = User.find(session[:user_id])
  end

  def update
    @user = User.find(session[:user_id])

    if !SEATS[params[:user][:table]].include?(params[:user][:seat])
      flash.now[:notice] = "Seat is not on selected table"
      render "edit"
      return
    end

    users_in_seat = User.where(:table => params[:user][:table], :seat => params[:user][:seat])
    if !users_in_seat.empty? and users_in_seat != [@user]
      flash.now[:notice] = "Someone else is sat there!"
      render "edit"
    elsif @user.update_attributes(params[:user])
      redirect_to root_url, :notice => "Profile updated!"
    else
      render "edit"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dev_helper.rb
module DevHelper
end

app/helpers/floor_plan_helper.rb
module FloorPlanHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dev/sha.html.erb
<h1>Dev#sha</h1>
<p>Find me in app/views/dev/sha.html.erb</p>

app/views/floor_plan/show.html.erb
<div class="floor_plan">
  <% @tables.each do |table| %>
    <h1><%= table["name"] %></h1>
    <table class="tables" id="<%=table["name"]%>">
      <% table["rows"].each do |row| %>
        <tr>
          <!-- Left End Table -->
          <% if END_TABLES[table["name"]].include? "L" %>
            <td class="end_table" style="width:<%= @longest_name %>em">
              <div class="seat" style="width: 100%">
                <% seat_name = row + "0" %>
                <% user = User.where(:table => table["name"], :seat => seat_name).first %>
                <% if !user.nil? %>
                  <%= user.username %>
                <% else %>
                  <%= seat_name %>
                <% end %>
              </div>

            </td>
          <% end %>

          <!-- Main Tables -->
          <% for j in 1..table["tables"] %>
            <td class="table" style="width:<%= @longest_name * table["seats_per_table"] %>em">
              <% for i in 1..table["seats_per_table"] %>
                <div class="seat" style="width:<%= 100 / table["seats_per_table"] %>%">
                  <% seat_num = (j-1)*table["seats_per_table"] + (i-1) %>
                  <% seat_num += 1 if END_TABLES[table["name"]].include? "L" %>
                  <% seat_name = row + seat_num.to_s %>
                  <% user = User.where(:table => table["name"], :seat => seat_name).first %>
                  <% if !user.nil? %>
                    <%= user.username %>
                  <% else %>
                    <%= seat_name %>
                  <% end %>
                </div>
              <% end %>
            </td>
          <% end %>

          <!-- Right End Table -->
          <% if END_TABLES[table["name"]].include? "R" %>
            <td class="end_table" style="width:<%= @longest_name %>em">
              <div class="seat" style="width: 100%">
                <% seat_num = table["tables"]*table["seats_per_table"] %>
                <% seat_num += 1 if END_TABLES[table["name"]].include? "L" %>
                <% seat_name = row + seat_num.to_s %>
                <% user = User.where(:table => table["name"], :seat => seat_name).first %>

                <% if !user.nil? %>
                  <%= user.username %>
                <% else %>
                  <%= seat_name %>
                <% end %>
              </div>
            </td>
          <% end %>
        </tr>
      <% end %>
    </table>
  <% end %>
</div>

app/views/games/new.html.erb
<h1>Add new game</h1>

<% if !@game %>
  <% @game = Game.new %>
<% end %>

<%= form_for @game do |f| %>
  <% if @game.errors.any? %>
    <div class="Error">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @game.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
  <%= f.label:name %><br>
  <%= f.text_field:name %>
  </p>
  <p>
  <%= f.label :url, "Steam Page/Website" %><br>
  <%= f.text_field:url %>
  </p>
  <p class="button"><%= f.submit %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>COGS Now Playing Board</title>
    <link rel="shortcut icon" href="#" />
    <%= stylesheet_link_tag 'http://fonts.googleapis.com/css?family=Rambla:400,700,400italic' %>
    <%= stylesheet_link_tag 'http://fonts.googleapis.com/css?family=Strait' %>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div id="user_nav">
      <div class="left">
        <%= link_to "Home", root_url %>
        <% if current_user %>
          <%= link_to "Create Post", posts_new_path %>
        <% else %>
          <%= link_to "Signup", signup_path %>
          <%= link_to "Login", login_path %>
        <% end %>
      </div>

      <div class="right">
        <% if current_user %>
          Logged in as <%= current_user.username %>
          <%= link_to "Edit Profile", users_edit_path %>
          <%= link_to "Logout", logout_path %>
        <% end %>
      </div>
    </div>

    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    <% end %>

    <%= yield %>

  </body>
</html>

app/views/posts/all.html.erb
<h1>Don't play with yourself!</h1>

<% @posts.each do |post| %>
  <% if !post.users.empty? %>
    <div class="post">
      <h1><%= link_to post.game.name, post.game.url %></h1>
      <% if current_user and !post.users.include? current_user %>
        <%= button_to "I want to play!", { :action => "add_user", :post_id => post.id, :user_id => current_user.id }, :form_class => "add_request", :method => "post" %>
      <% end %>
      <% if !post.params.nil? %>
        <h2><%= post.params %></h2>
      <% end %>
      <% post.users.each do |player| %>
        <div class="request">
          <h3><%= player.username %> wants to play</h3>
          <% if player.id == session[:user_id] %>
            <%= button_to "Delete", { :action => "del_user", :id => post.id, :user_id => player.id }, :form_class => "delete_request", :confirm => "Are you sure?", :method => "delete" %>
          <% end %>
        </div>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/posts/destroy.html.erb
<h1>Posts#delete</h1>
<p>Find me in app/views/posts/delete.html.erb</p>

app/views/posts/new.html.erb
<h1>Create a new post</h1>

<%= form_for @post do |f| %>
  <% if @post.errors.any? %>
    <div class="Error">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @post.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
  <%= f.label :game %>
  <%= f.collection_select(:game, Game.find(:all, :order => "name"), :id, :name, :prompt => true) %>
  </p>
  <p>
  <%= f.label :params, "Game Parameters" %>
  <%= f.text_field :params, :placeholder => "eg GunGame on cs_office" %>
  </p>
  <p><%= link_to "Add a new game", games_new_path %></p>
  <p class="button"><%= f.submit %></p>
<% end %>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="Error">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
  <%= f.label :username %><br>
  <%= f.text_field :username, :value => @user.username %>
  </p>
  <p>
  Where are you sat?<br>
  <%= f.label :table, "Table: " %><%= f.select :table, @tables %>
  <br>
  <%= f.label :seat, "Seat: " %><%= f.select :seat, @seats %>
  <%= link_to "Floor Plan", {:controller => "floor_plan", :action => "show"}, :target => "_blank"%>
  </p>
  <p>
  <%= f.label :comment, "How else can people contact you?" %><br>
  <%= f.text_field :comment, :value => @user.comment %>
  </p>
  <p class="button"><%= f.submit %></p>
<% end %>

app/views/users/edit.html.erb
<h1>Change Profile</h1>

<%= render 'form' %>

app/views/users/new.html.erb
<h1>Signup</h1>

<%= render 'form' %>